# Generated by Django 3.1 on 2020-08-12 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ekmek', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekmek',
            name='ekmekDetayi',
            field=models.TextField(default='', verbose_name='Detay'),
        ),
        migrations.AlterField(
            model_name='ekmek',
            name='ekmekAdi',
            field=models.CharField(max_length=50, verbose_name='Ekmek Cinsi'),
        ),
        migrations.AlterField(
            model_name='ekmek',
            name='uretici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Üretici'),
        ),
    ]
