# Generated by Django 3.1 on 2020-08-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekmek', '0003_auto_20200812_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekmek',
            name='durum',
            field=models.CharField(choices=[('Sicak', 'Sicak'), ('Soguk', 'Soguk')], default='Soguk', max_length=5),
        ),
        migrations.AlterField(
            model_name='ekmek',
            name='stok',
            field=models.CharField(choices=[('Var', 'Var'), ('Yok', 'Yok')], default='Yok', max_length=3),
        ),
    ]
