# Generated by Django 3.1 on 2020-08-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekmek', '0005_ekmek_sonsicak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekmek',
            name='sonSicak',
            field=models.DateField(blank=True, null=True, verbose_name='Son Sicak Cikis Tarihi'),
        ),
    ]
