# Generated by Django 3.1 on 2020-08-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekmek', '0006_auto_20200813_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekmek',
            name='sonSicak',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Sicak Cikis Tarihi'),
        ),
    ]
