# Generated by Django 3.1 on 2020-08-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekmek', '0008_auto_20200813_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekmek',
            name='sonSicak',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Son Sicak Cikis Tarihi'),
        ),
    ]
