# Generated by Django 3.1 on 2020-08-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekmek', '0009_auto_20200813_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekmek',
            name='durum',
            field=models.CharField(choices=[('Sicak', 'Sicak'), ('Soguk', 'Soguk'), ('-', '-')], default='Soguk', max_length=5),
        ),
    ]
