# Generated by Django 3.1 on 2020-08-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekmek', '0010_auto_20200814_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekmek',
            name='ekmekResmi',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Ekmek Resmi Ekle'),
        ),
    ]
