# Generated by Django 3.1 on 2020-09-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekmek', '0012_auto_20200815_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekmek',
            name='sonSicak',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Sicak Cikis Tarihi'),
        ),
    ]
