# Generated by Django 3.1 on 2020-09-12 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekmek', '0013_auto_20200913_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekmek',
            name='durum',
        ),
        migrations.RemoveField(
            model_name='ekmek',
            name='stok',
        ),
    ]
