# Generated by Django 3.1 on 2020-09-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekmek', '0014_auto_20200913_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekmek',
            name='sonSicak',
            field=models.CharField(blank=True, default='1 Ocak 1970', max_length=40, null=True, verbose_name='Sicak Cikis Tarihi'),
        ),
    ]
