# Generated by Django 3.1 on 2020-09-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekmek', '0016_auto_20200915_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekmek',
            name='ekmekResmi',
        ),
    ]
