# Generated by Django 3.1 on 2020-09-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekmek', '0017_remove_ekmek_ekmekresmi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ekmek',
        ),
    ]
