# Generated by Django 3.1 on 2020-08-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200816_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telefonNumarasi',
            field=models.IntegerField(default=True, null=True),
        ),
    ]
