# Generated by Django 3.1 on 2020-09-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_telefonnumarasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilResmi',
            field=models.ImageField(blank=True, default='/static/finalLogo.png', null=True, upload_to='profil/', verbose_name='Profil Resmi Ekle'),
        ),
    ]
