# Generated by Django 3.1 on 2020-09-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200911_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adres',
            field=models.CharField(default='Kayitli Adres Bulunmuyor', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='profile',
            name='long',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefonNumarasi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
